notifications:
  email: false

sudo: required

services:
  - docker

script:
  - docker-compose build
  - docker-compose run concha_user /bin/sh -c "npm run lint && npm test"

after_script:
  - docker-compose down
