version: "3"

volumes:
  database:

services:

  mongo:
    container_name: mongo
    image: mongo:3.0.15-wheezy
    ports:
      # Expose port to host machine for debugging
      - 27017
    volumes:
      - database:/data/db

  concha_user:
    container_name: concha_user
    build: .
    volumes:
      # Make the following directories available to docker so that changes made on the host
      # are immediately available inside the docker container.
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./npm-shrinkwrap.json:/app/npm-shrinkwrap.json
    command: npm run debug
    ports:
      # Expose port to host machine for debugging
      - 80:80
    links:
      - mongo
