version: "3"
services:

  mongo:
    image: mongo
    ports:
      - 27017:27017

  concha_user:
    build: .
    volumes:
      - ./src:/app/src
    # command: - npm start
    ports:
      - 3001:80
    links:
      - mongo
