version: "3"
services:

  mongo:
    container_name: mongo_concha_user
    image: mongo:3.0.15-wheezy
    ports:
      # Expose port to host machine for debugging
      - 27017:27017

  concha_user:
    container_name: concha_user
    build: .
    volumes:
      # Make the following directories available to docker so that changes made on the host
      # are immediately available inside the docker container.
      - ./src:/app/src
      - ./test:/app/test

      # Make package.json available to Docker so that new packages added during the test/develop
      # lifecycle are reflected back to the host, where they can be commited to github.
      - ./package.json:/app/package.json

      # Make npm-shrinkwrap.json available to Docker so that changes made by npm shrinkwrap 
      # in the docker container are reflected back to the host, where they can be committed to
      # github.
      - ./npm-shrinkwrap.json:/app/npm-shrinkwrap.json
    command: npm run debug
    ports:
      # Expose port to host machine for debugging
      - 80:80
    links:
      - mongo
